[2024-09-11T17:55:05.223+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T17:55:06.060+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-11T17:50:00+00:00 [queued]>
[2024-09-11T17:55:06.118+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-11T17:50:00+00:00 [queued]>
[2024-09-11T17:55:06.120+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-11T17:55:06.350+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): correct_1nf_violations> on 2024-09-11 17:50:00+00:00
[2024-09-11T17:55:06.724+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_1FN', 'correct_1nf_violations', 'scheduled__2024-09-11T17:50:00+00:00', '--job-id', '1284', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_1FN.py', '--cfg-path', '/tmp/tmp16po4sfv']
[2024-09-11T17:55:06.834+0000] {standard_task_runner.py:105} INFO - Job 1284: Subtask correct_1nf_violations
[2024-09-11T17:55:06.939+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19157) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T17:55:06.956+0000] {standard_task_runner.py:72} INFO - Started process 19184 to run task
[2024-09-11T17:55:11.943+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-11T17:50:00+00:00 [running]> on host b8b5351e8a6b
[2024-09-11T17:55:14.098+0000] {job.py:229} INFO - Heartbeat recovered after 11.43 seconds
[2024-09-11T17:55:16.873+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_1FN' AIRFLOW_CTX_TASK_ID='correct_1nf_violations' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T17:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T17:50:00+00:00'
[2024-09-11T17:55:16.895+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T17:55:17.702+0000] {logging_mixin.py:190} INFO - Erreur lors de la correction des anomalies : column "product_ids" does not exist
LINE 2:         SELECT customer_id, product_ids, order_date, total_a...
                                    ^
[2024-09-11T17:55:17.709+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T17:55:18.256+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T17:55:18.259+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_1FN, task_id=correct_1nf_violations, run_id=scheduled__2024-09-11T17:50:00+00:00, execution_date=20240911T175000, start_date=20240911T175506, end_date=20240911T175518
[2024-09-11T17:55:18.724+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T17:55:19.561+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T17:55:19.568+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
