[2024-09-13T15:01:51.209+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T15:01:53.208+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_detect_invalid_customer_ids.run_anomaly_detection scheduled__2024-09-13T14:45:00+00:00 [queued]>
[2024-09-13T15:01:53.303+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_detect_invalid_customer_ids.run_anomaly_detection scheduled__2024-09-13T14:45:00+00:00 [queued]>
[2024-09-13T15:01:53.306+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T15:01:53.724+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-13 14:45:00+00:00
[2024-09-13T15:01:53.822+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8757) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T15:01:53.830+0000] {standard_task_runner.py:72} INFO - Started process 8850 to run task
[2024-09-13T15:01:53.819+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_detect_invalid_customer_ids', 'run_anomaly_detection', 'scheduled__2024-09-13T14:45:00+00:00', '--job-id', '2563', '--raw', '--subdir', 'DAGS_FOLDER/dag_detect_invalid_customer_ids.py', '--cfg-path', '/tmp/tmpvg4it4d_']
[2024-09-13T15:01:53.841+0000] {standard_task_runner.py:105} INFO - Job 2563: Subtask run_anomaly_detection
[2024-09-13T15:01:57.760+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_detect_invalid_customer_ids.run_anomaly_detection scheduled__2024-09-13T14:45:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T15:01:59.785+0000] {job.py:229} INFO - Heartbeat recovered after 101.35 seconds
[2024-09-13T15:02:01.546+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_detect_invalid_customer_ids' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T14:45:00+00:00'
[2024-09-13T15:02:01.554+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T15:02:01.643+0000] {dag_detect_invalid_customer_ids.py:101} INFO - Starting anomaly detection process
[2024-09-13T15:02:04.198+0000] {dag_detect_invalid_customer_ids.py:105} INFO - Loaded 15 transactions
[2024-09-13T15:02:04.278+0000] {dag_detect_invalid_customer_ids.py:108} INFO - Detected 4 anomalies
[2024-09-13T15:02:04.334+0000] {dag_detect_invalid_customer_ids.py:94} INFO - Inserted 4 new anomalies.
[2024-09-13T15:02:04.336+0000] {dag_detect_invalid_customer_ids.py:111} INFO - Anomaly detection process completed successfully
[2024-09-13T15:02:04.339+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T15:02:05.307+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T15:02:05.325+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_detect_invalid_customer_ids, task_id=run_anomaly_detection, run_id=scheduled__2024-09-13T14:45:00+00:00, execution_date=20240913T144500, start_date=20240913T150153, end_date=20240913T150205
[2024-09-13T15:02:05.534+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T15:02:06.354+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
