[2024-09-10T21:05:17.740+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T21:05:19.242+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-10T21:00:00+00:00 [queued]>
[2024-09-10T21:05:19.303+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-10T21:00:00+00:00 [queued]>
[2024-09-10T21:05:19.305+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-10T21:05:19.409+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-10 21:00:00+00:00
[2024-09-10T21:05:19.446+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5109) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T21:05:19.460+0000] {standard_task_runner.py:72} INFO - Started process 5151 to run task
[2024-09-10T21:05:19.451+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'detect_transaction_date_anomalies_dag', 'run_anomaly_detection', 'scheduled__2024-09-10T21:00:00+00:00', '--job-id', '3444', '--raw', '--subdir', 'DAGS_FOLDER/Dag-Transaction-Date-in-the-Paste.py', '--cfg-path', '/tmp/tmp5_8yp7tl']
[2024-09-10T21:05:19.482+0000] {standard_task_runner.py:105} INFO - Job 3444: Subtask run_anomaly_detection
[2024-09-10T21:05:21.099+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-10T21:00:00+00:00 [running]> on host f0946a6cef1f
[2024-09-10T21:05:23.683+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='detect_transaction_date_anomalies_dag' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-10T21:00:00+00:00'
[2024-09-10T21:05:23.686+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T21:05:25.304+0000] {job.py:229} INFO - Heartbeat recovered after 12.39 seconds
[2024-09-10T21:05:25.408+0000] {Dag-Transaction-Date-in-the-Paste.py:97} INFO - Inserting 1 detected anomalies
[2024-09-10T21:05:36.423+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-10T21:05:36.639+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T21:05:36.640+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_transaction_date_anomalies_dag, task_id=run_anomaly_detection, run_id=scheduled__2024-09-10T21:00:00+00:00, execution_date=20240910T210000, start_date=20240910T210519, end_date=20240910T210536
[2024-09-10T21:05:36.905+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T21:05:37.427+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T21:05:37.435+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
