[2024-09-10T21:05:18.536+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T21:05:19.439+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-10T21:00:00+00:00 [queued]>
[2024-09-10T21:05:19.524+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-10T21:00:00+00:00 [queued]>
[2024-09-10T21:05:19.526+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-10T21:05:19.627+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-10 21:00:00+00:00
[2024-09-10T21:05:19.673+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5105) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T21:05:19.668+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_Non-numeric-Quantity', 'run_anomaly_detection', 'scheduled__2024-09-10T21:00:00+00:00', '--job-id', '3445', '--raw', '--subdir', 'DAGS_FOLDER/Dag_Non-numeric-Quantity.py', '--cfg-path', '/tmp/tmpvfr3bjq6']
[2024-09-10T21:05:19.698+0000] {standard_task_runner.py:72} INFO - Started process 5153 to run task
[2024-09-10T21:05:19.699+0000] {standard_task_runner.py:105} INFO - Job 3445: Subtask run_anomaly_detection
[2024-09-10T21:05:21.580+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-10T21:00:00+00:00 [running]> on host f0946a6cef1f
[2024-09-10T21:05:23.898+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_Non-numeric-Quantity' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-10T21:00:00+00:00'
[2024-09-10T21:05:23.909+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T21:05:24.065+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-10T21:05:24.928+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T21:05:24.932+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_Non-numeric-Quantity, task_id=run_anomaly_detection, run_id=scheduled__2024-09-10T21:00:00+00:00, execution_date=20240910T210000, start_date=20240910T210519, end_date=20240910T210524
[2024-09-10T21:05:25.448+0000] {job.py:229} INFO - Heartbeat recovered after 10.53 seconds
[2024-09-10T21:05:26.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T21:05:26.827+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T21:05:26.846+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
