[2024-09-13T22:20:40.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T22:20:43.207+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T22:15:00+00:00 [queued]>
[2024-09-13T22:20:43.272+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T22:15:00+00:00 [queued]>
[2024-09-13T22:20:43.275+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T22:20:43.452+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-13 22:15:00+00:00
[2024-09-13T22:20:43.547+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=78750) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T22:20:43.565+0000] {standard_task_runner.py:72} INFO - Started process 78835 to run task
[2024-09-13T22:20:43.587+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_Non-numeric-Quantity', 'run_anomaly_detection', 'scheduled__2024-09-13T22:15:00+00:00', '--job-id', '3812', '--raw', '--subdir', 'DAGS_FOLDER/Dag_Non-numeric-Quantity.py', '--cfg-path', '/tmp/tmp60zpr4_x']
[2024-09-13T22:20:43.635+0000] {standard_task_runner.py:105} INFO - Job 3812: Subtask run_anomaly_detection
[2024-09-13T22:20:52.704+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T22:15:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T22:20:53.134+0000] {job.py:229} INFO - Heartbeat recovered after 18.79 seconds
[2024-09-13T22:21:05.398+0000] {job.py:229} INFO - Heartbeat recovered after 12.41 seconds
[2024-09-13T22:21:28.051+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_Non-numeric-Quantity' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T22:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T22:15:00+00:00'
[2024-09-13T22:21:28.696+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T22:21:35.367+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T22:21:39.111+0000] {job.py:229} INFO - Heartbeat recovered after 33.74 seconds
[2024-09-13T22:21:39.287+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T22:21:39.590+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_Non-numeric-Quantity, task_id=run_anomaly_detection, run_id=scheduled__2024-09-13T22:15:00+00:00, execution_date=20240913T221500, start_date=20240913T222043, end_date=20240913T222139
[2024-09-13T22:21:42.564+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T22:21:43.130+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-13T22:21:46.062+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T22:21:46.084+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
